### ISSUE TITLE
JSBasics Grading

### ISSUE THREAD

**Issue by wesharper** [webfun-sept2017/RossAllan-webfun-2017#1]
#main should be next to #navbar on the right.
https://github.com/webfun-sept2017/RossAllan-webfun-2017/blob/886a9e536a32eb812f17291e23e778a1cbe10c5f/WebFundamentals/CSS/JavaScript%20Basics/style.css#L27

**Comment by Uranupt** [comment]
I'm not sure what you mean. It displays the way it is in the example image for me, to the right vertically aligned with the top.

**Comment by wesharper** [comment]
Maybe my browser window was too small, but I wasn't rendering the same thing you're seeing.
