### ISSUE TITLE
Plotting Your Blocks Grading

### ISSUE THREAD

**Issue by wesharper** [webfun-sept2017/RossAllan-webfun-2017#2]
Nav should be vertically aligned with subcontents.
https://github.com/webfun-sept2017/RossAllan-webfun-2017/blob/886a9e536a32eb812f17291e23e778a1cbe10c5f/WebFundamentals/CSS/CSS%20Blocks/style.css#L17

**Comment by Uranupt** [comment]
Thank you, I have resolved this.

**Comment by wesharper** [comment]
Great!
